const storedTasks = [
  {
    userID: null,
    completed: false,
    taskName: 'Laundry',
    dueDate: 'Fri Nov 5 2018',
    description: 'Darks First',
    taskID: 1,
    dateAdded: 'Fri Oct 20 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Make Costume',
    dueDate: undefined,
    description: 'Add lace collar',
    taskID: 2,
    dateAdded: 'Fri Oct 22 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Update Jira Board',
    dueDate: 'Fri Nov 5 2018',
    description: 'Add functionality cards',
    taskID: 3,
    dateAdded: 'Fri Oct 27 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Eat Candy',
    dueDate: undefined,
    description: 'especially snickers',
    taskID: 4,
    dateAdded: 'Fri Oct 30 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Play with Black Cat',
    dueDate: 'Fri Nov 4 2018',
    description: 'at least half an hour',
    taskID: 5,
    dateAdded: 'Fri Nov 1 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Cook a Turkey',
    dueDate: undefined,
    description: 'no more than 15 pounds!',
    taskID: 6,
    dateAdded: 'Fri Nov 2 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Higher Level Test',
    dueDate: 'Fri Nov 3 2018',
    description: 'Darks First',
    taskID: 7,
    dateAdded: 'Fri Nov 3 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Level Test',
    dueDate: undefined,
    description: 'especially snickers',
    taskID: 8,
    dateAdded: 'Fri Nov 4 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Play the lotto',
    dueDate: 'Fri Nov 1 2018',
    description: 'Win the jackpot',
    taskID: 9,
    dateAdded: 'Fri Nov 5 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Mow the lawn',
    dueDate: undefined,
    description: 'when it grows',
    taskID: 10,
    dateAdded: 'Fri Nov 5 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Level Test',
    dueDate: 'Fri Nov 9 2018',
    description: 'whooo',
    taskID: 11,
    dateAdded: 'Fri Nov 6 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Make explosions',
    dueDate: undefined,
    description: 'especially snickers',
    taskID: 12,
    dateAdded: 'Fri Nov 6 2018',
  }
];

export default storedTasks;
