const storedTasks = [
  {
    userID: null,
    completed: false,
    taskName: 'Laundry',
    dueDate: 'Fri Oct 10 2018',
    description: 'Darks First',
    taskID: 1,
    dateAdded: 'Fri Oct 5 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Make Costume',
    dueDate: 'Fri Oct 31 2018',
    description: 'Add lace collar',
    taskID: 2,
    dateAdded: 'Fri Oct 15 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Update Jira Board',
    dueDate: undefined,
    description: 'Add functionality cards',
    taskID: 3,
    dateAdded: 'Fri Oct 30 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Eat Candy',
    dueDate: 'Fri Nov 1 2018',
    description: 'especially snickers',
    taskID: 4,
    dateAdded: 'Fri Oct 28 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Play with Black Cat',
    dueDate: undefined,
    description: 'at least half an hour',
    taskID: 5,
    dateAdded: 'Fri Oct 29 2018',
  },
  {
    userID: null,
    completed: false,
    taskName: 'Cook a Turkey',
    dueDate: 'Fri Nov 18 2018',
    description: 'no more than 15 pounds!',
    taskID: 6,
    dateAdded: 'Fri Oct 15 2018',
  },
];

export default storedTasks;
